### ISSUE TITLE
Integrate new static starter & sketch 

### ISSUE THREAD

**Issue by roybarber** [wearedamage/wordpress-starter#5]

**Comment by roybarber** [comment]
@holliepearson implement the latest version of static-starter CSS/ into this theme

You may need to edit functions.php with the right CSS refrence

**Comment by roybarber** [comment]
Was this just copied and pasted in @holliepearson ?

**Comment by holliepearson** [comment]
I think so, was that not right?

**Comment by roybarber** [comment]
nope:

"You may need to edit functions.php with the right CSS refrence"

If you'd have ran the site you would see its not the new CSS, when you run gulp it creates the main.css file thats not tracked in the repo, so grunt must never have been run, meaning it was never tested.

<img width="468" alt="screen shot 2017-06-14 at 17 20 37" src="https://user-images.githubusercontent.com/2923782/27143301-d2afff78-5125-11e7-955d-d5c13e660c41.png">
